### PR TITLE
Bugfix/purs version incompatability scope example

### PR DESCRIPTION
**Pull request by SuperCipher**
@rnons 
scope: example folder
add purescript and spago to npm devdependency
update readme

### CODE REVIEW

**Comment by rnons** [comment]
Thanks. The problem is I have lots of purescript-* packages, I don't want to install purs+spago to each of them, so I'm using global install.

**Comment by SuperCipher** [comment]
Thanks for the fast reply. @rnons 
This is just for example folder so it should not impact the source code.
In my case I got a lot of Purescript project that use different Purescript version . I prefer that every project should only depend on local version also for repoducability reason.

**Comment by rnons** [comment]
Is `nix` an option to you? I pushed https://github.com/rnons/purescript-halogen-storybook/commit/b8ab26486e22cc3e147bff5bee6564695a3a9b72 just now, run

```
nix-shell
# wait a few seconds
purs --version
spago version
```

**Comment by SuperCipher** [comment]
@ that's seems to not work for me
Screen Shot 2021-03-19 at 16 49 02
```
[nix-shell:~/dev/sandbox2/purescript-halogen-storybook]$ purs --version
bash: /nix/store/1nkbr1dqj0n41yssl1hb3x5lxlzklsa9-purs/bin/purs: cannot execute binary file: Exec format error

[nix-shell:~/dev/sandbox2/purescript-halogen-storybook]$ spago version
bash: /nix/store/fhh33wpy6r83y75qypsl72wac4sdhg74-spago/bin/spago: cannot execute binary file: Exec format error
```

Also with this pull request, you still be able to use your global install purs and spago as usual. It just allows new commer to install all package locally which make running an example less prone to version conflict.

**Comment by rnons** [comment]
Thanks

**Pull request merged**
