### PR TITLE
lift to PureScript 0.15

### PR DESCRIPTION
**Pull request by CarstenKoenig**
- upgraded package-set
- updated dependencies with hints from spago build
- fixed type error with `launch_`

### CODE REVIEW

**Review by JordanMartinez — CHANGES_REQUESTED** [review]
You'll need to update the dependencies in the `bower.json` file, too. Otherwise, we won't be able to push docs for this library or any other library that depends on it to Pursuit.

**Comment by thomashoneyman** [comment]
👍 from me

**Comment by CarstenKoenig** [comment]
> You'll need to update the dependencies in the bower.json file, too. 

Sorry - one seconde - fro some reason I thought this is auto-generated by spago/pulp

**Comment by thomashoneyman** [comment]
> > You'll need to update the dependencies in the bower.json file, too.
> 
> Sorry - one seconde - fro some reason I thought this is auto-generated by spago/pulp

It _can_ be auto-generated by Spago, but it's often easier to just bump all the versions by a major version by hand and check with `bower install && npx pulp build`.

**Comment by CarstenKoenig** [comment]
Ok I tried to update the file and include all the dependency-versions as mentioned in the psc-file.
But it seems that bower is unable to resolve a fitting set.

Any hints for me (sorry it's really been a while since I tried to handle bower dependencies directly)

**Comment by JordanMartinez** [comment]
If you run `bower cache clean && rm -rf bower_components && bower i`, then things will likely work.

**Comment by CarstenKoenig** [comment]
well sadly only *kindof*

If I keep all the dependencies (those spago detects and recommends) then I'll run into mismatching versions while `bower i`.
If I keep the dependencies from the original `bower.json` with only the versions bumped `bower i` succeeds but it pulls packages that still use commonjs and `pulp build` ends up with errors like this:

```
[1/7 DeprecatedFFICommonJSModule] bower_components/purescript-integers/src/Data/Int/Bits.purs:2:1

      v
   2  module Data.Int.Bits
   3    ( and, (.&.)
   4    , or, (.|.)
      ...
  35  
  36  -- | Bitwise NOT.
  37  foreign import complement :: Int -> Int                                        ^
```

sticking with this example bower chooses integers-5.0.0 and as far as I can tell this is because `strings-5.0` is in `halogen-6.1.3` and `string-5.0.0` wants `integers-5.0.0`.

halogen-7.0 seems ok in this regards but some other dependency seems to resolve aff into 6.0.0 and so on.

I guess I'll probably have to wait till more dependencies settle in and retry?
```

**Comment by thomashoneyman** [comment]
@CarstenKoenig Unfortunately generating from Spago is not great when there's been a lot of recent breaking changes, because the package sets don't obey version ranges. It's also lackluster when the project doesn't have separate files for test and production dependencies, because they all get put into the bower.json file instead of just the production ones.

**Comment by CarstenKoenig** [comment]
> @CarstenKoenig Unfortunately generating from Spago is not great when there's been a lot of recent breaking changes, because the package sets don't obey version ranges. It's also lackluster when the project doesn't have separate files for test and production dependencies, because they all get put into the bower.json file instead of just the production ones.

I'm sure I did something wrong but just to clarify: I did not use spago to generate the bower.json - I just added the packages that spago recommended to include (in spago.dhall) - my assumption was that those are the used dependencies.

Then I looked in the package-set that spago found/upgrded fo the versions - I guess here I was wrong.

What's the better way? Clear out bower.json and start from scratch?

**Comment by CarstenKoenig** [comment]
@thomashoneyman thanks for the update (hope this works) - I'm a bit confused that there is no dependency to halogen in the new bower.json.  Is this a workaround or is this really not needed?

**Comment by thomashoneyman** [comment]
> What's the better way? Clear out bower.json and start from scratch?

When there is a major compiler release, pretty much every dependency is going to move up a major version because it depends on something that also moved up a major version (like `prelude`). So what I generally do is just take the existing Bowerfile and bump everything by a major version :)

**Comment by thomashoneyman** [comment]
> I'm a bit confused that there is no dependency to halogen in the new bower.json.

I think that's just the diff of it moving to a new place in the list of dependencies. It's still in there (at v7.0.0).

**Comment by CarstenKoenig** [comment]
> > I'm a bit confused that there is no dependency to halogen in the new bower.json.
> 
> I think that's just the diff of it moving to a new place in the list of dependencies. It's still in there (at v7.0.0).

Damn ... feeling quite stupid right now ... sorry

**Comment by thomashoneyman** [comment]
Well, it _is_ deleted in the diff, so it’s an understandable miss! I’ve done it myself a number of times.

**Review by thomashoneyman — APPROVED** [review]

**Comment by thomashoneyman** [comment]
https://github.com/rnons/purescript-halogen-storybook/releases/tag/v2.0.0

**Comment by CarstenKoenig** [comment]
Thank you for helping out and merging this mess ;)

**Pull request merged**
